### ISSUE TITLE
bug: Session Fails to Set When Exceeding Data Size Limit

### ISSUE THREAD

**Issue by fayazara** [Atinux/nuxt-auth-utils#75] opened 2024-04-07 06:09 UTC
### Description:
While implementing session management with the nuxt-auth-utils library, I encountered a very hard to debug issue where the session fails to set/update with a slightly large amount of data. 

### How did I discover this?
One of the user entered a large amount of data to my users table field called "bio", the next time they logged in this data was getting included in the session, I have now removed this added a limit to this field. This kept breaking auth flow because the session was never getting set, and always returned a 401 when this specific user tried logging in, this can be handled in the `setUserSession` method

### Steps to Reproduce:

1. Initialize a session for a user with a minimal amount of data.
2. The next time they login, set the session with additional data, gradually increasing the total size.
3. Observe the behavior of the session update functionality as the total session data size approaches and exceeds 4KB (max cookie size)

### Suggested Remedies:
- Throw an error stating the cookie is getting too large, instead of continuing, made this quite hard to figure out the issue

### Environment:

nuxt-auth-utils Version: ^0.0.22
Nuxt Version: 3.11.2
Browser/Node.js Version: Chrome 123.0.6312.107
Platform: Macos Sonoma

**Comment by fayazara** [comment] 2024-04-07 06:10
I will try to work on this and raise a PR

**Comment by Atinux** [comment] 2024-04-08 09:05
Closing as duplicate of #41 

One solution at the moment is to only keep the minimal & required data for the backend in the session.

And use the [session hooks](https://github.com/Atinux/nuxt-auth-utils?tab=readme-ov-file#extend-session) to extend for the frontend (bio is an example)

**Closed by Atinux** 2024-04-08 09:05 UTC
