### ISSUE TITLE
A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file instead?

### ISSUE THREAD

**Issue by jonasfroeller** [atinux/nuxt-auth-utils#191] opened 2024-09-26 01:16 UTC
------------------------------
- Operating System: Windows_NT
- Node Version:     v18.19.0
- Nuxt Version:     3.13.2
- CLI Version:      3.14.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.1.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

![image](https://github.com/user-attachments/assets/7a23dc6d-379f-4407-b9d6-997bef75b611)

I have no idea why this happens now, but I can not work on my project, till I solve this.  
I used auth utils for 2 months and didn't have any issues.

This fixes the issue:
```ts
  "pnpm": {
    "overrides": {
      "vite-plugin-checker": "0.8.0",
      "vue-tsc": "2.0.29",
    }
  }
  ```

but introduces another error

![image](https://github.com/user-attachments/assets/baa3d49d-e408-46eb-a7e2-e858ca95686a)

I think this issue belongs in vue-tsc, but I just had issues with vue-tsc when I used auth utils.

**Comment by FlorientPlouvin** [comment] 2024-10-07 12:53
Got the exact same issue, not sure it's a good idea to downgrade vue-tsc version

**Comment by Vterebenin** [comment] 2024-10-11 13:01
Same here... had to make `autoImport: false` in a `nuxt.config.ts` to resolve issue

**Comment by stefanschlipfi** [comment] 2024-10-18 09:54
I got the same issue.

**Comment by Bombastickj** [comment] 2024-11-18 17:46
I am having the same issue!

**Comment by DrFuehrer02** [comment] 2024-11-20 10:19
@atinux @stranavad

**Comment by kofeinstyle** [comment] 2024-11-20 22:13
The same issue. Maybe this is related with `compatibilityVersion: 4` option?

**Comment by Bombastickj** [comment] 2024-11-21 09:15
> The same issue. Maybe this is related with `compatibilityVersion: 4` option?

Unfortunately not, this minimal reproduction is not set to `compatibilityVersion: 4`.

https://stackblitz.com/edit/github-mmpbcp?file=nuxt.config.ts

**Comment by gygoo** [comment] 2024-11-25 11:51
I got the same issue.

`
"nuxt": "^3.14.1592",
 "vue": "latest",

"typescript": "^5.7.2",
"vue-tsc": "^2.1.10"
 `

and:
` future: {
    compatibilityVersion: 4,
  },

  experimental: {
    asyncContext: true,
  },
`

**Comment by nathanchase** [comment] 2024-11-25 13:25
If you take out 

```ts
typescript: {
    shim: false,
    typeCheck: true,
    strict: true,
  },
```

from https://stackblitz.com/edit/github-mmpbcp?file=nuxt.config.ts

the errors go away.

No errors: https://stackblitz.com/edit/github-mmpbcp-qxqvaj?file=nuxt.config.ts

**Comment by gygoo** [comment] 2024-11-25 19:10
Removing:
`typeCheck: true,`
disables type validation, so there are no errors, but there is also no validation.

**Comment by nathanchase** [comment] 2024-11-28 02:36
> Removing: `typeCheck: true,` disables type validation, so there are no errors, but there is also no validation.

FWIW, `shim: false` and `strict: true` are the defaults:
https://nuxt.com/docs/api/nuxt-config#shim
https://nuxt.com/docs/api/nuxt-config#strict

**Comment by bpdid** [comment] 2024-12-02 16:09
Also getting these errors. Set `typeCheck` to `false` for now, but would prefer to keep it on.

**Comment by danielroe** [comment] 2024-12-05 13:48
I believe this is the source issue: https://github.com/vuejs/language-tools/issues/5018.

**Comment by bpdid** [comment] 2024-12-05 14:13
Just tried downgrading Typescript. It's the same with 5.6.x. The latest version that doesn't throw the error is 5.5.4.

**Comment by gygoo** [comment] 2024-12-05 14:20
Are you sure that version 5.5.4 is ok? I still have these errors with this version.

**Comment by bpdid** [comment] 2024-12-05 14:32
Yep. Make sure you have 5.5.4 installed by running `npm ls typescript` and cleanup with `npx nuxi cleanup`.

**Comment by danielroe** [comment] 2024-12-05 15:32
ah, if that's the case then my previous comment does not apply - there may be an issue here or in https://github.com/nitrojs/nitro.

**Comment by danielroe** [comment] 2024-12-05 15:43
Okay, here's what I've found.

This is caused by `unimport` generating the following code in `.nuxt/nitro-imports.d.ts`

```ts
declare global {
  // @ts-ignore
  export type { OAuthAuth0Config } from '/project/node_modules/.pnpm/nuxt-auth-utils/node_modules/nuxt-auth-utils/dist/runtime/server/lib/oauth/auth0.d.ts'
  import('/project/node_modules/.pnpm/nuxt-auth-utils/node_modules/nuxt-auth-utils/dist/runtime/server/lib/oauth/auth0.d.ts')
}
```

This dynamic `import()` was [added over a year ago](https://github.com/unjs/unimport/commit/8ee5a1d8411d3f3a9c2cbc2e6e04c4cc9c8425c8) and isn't the issue - the issue is the extension (`.d.ts`) which should instead be `.js` or omitted entirely.

This issue likely needs to be resolved in `unimport` (cc: @antfu) unless these types are not meant to be globally available.

**Comment by MasterCarl** [comment] 2024-12-20 09:01
We also encountered the error after upgrading Nuxt to `3.14.1592`. Downgrading to `3.13.1` resolved the issue again.

**Comment by danielroe** [comment] 2024-12-20 10:18
@MasterCarl instead, just upgrade `unimport` - that was where the issue was solved. (regenerating your lockfile should also work)

**Comment by danielroe** [comment] 2024-12-20 10:19
@atinux this should be good to close 👍

**Closed** 2024-12-20 10:50 UTC
