### ISSUE TITLE
[Google] Not possible to provide extra config for authorization

### ISSUE THREAD

**Issue by harlan-zw** [Atinux/nuxt-auth-utils#48] opened 2024-02-07 05:16 UTC
When authorizing with google, these params are hardcoded

```ts
response_type: "code",
client_id: config.clientId,
redirect_uri: redirectUrl,
scope: config.scope.join(" ")
```

However, several other options can be provided here. See https://developers.google.com/identity/protocols/oauth2/web-server#httprest_3

What is currently blocking me is `access_type` that allows you to specify `offline`, which is the only way to get a `refresh_token`, which is the only way to keep the user logged in for more than 1 hour (when they need to access Google APIs).

Maybe an option like `useRuntimeConfig(event).oauth.google.authorizationParams`

```ts
config: {
    redirectUrl: '/auth/google',
    scope: [
      'https://www.googleapis.com/auth/userinfo.email',
    ],
    authorizationParams: {
      prompt: 'consent',
      access_type: 'offline',
    },
  },
```

**Comment by Atinux** [comment] 2024-02-17 15:07
Closing as duplicate of #22

**Closed by Atinux** 2024-02-17 15:07 UTC
